config/routes.rb
Rails.application.routes.draw do
  resources :generos
  resources :filmes
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/filme.rb
class Filme < ApplicationRecord
    has_one_attached :capa
    belongs_to :genero, required: false
    paginates_per 4    
    
    def self.buscar_filme(filme)
        if filme
            filme_id = self.select(:id).where("titulo LIKE ?", "%" + sanitize_sql_like(filme) + "%")
            if filme_id.exists?
                @filmes = Filme.where(id: filme_id)
            else
                @filmes = nil
            end
        else
            @filmes = Filme.all            
        end
    end
end

app/models/genero.rb
class Genero < ApplicationRecord
    has_many :filme   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/filmes_controller.rb
class FilmesController < ApplicationController
  before_action :set_filme, only: [:show, :edit, :update, :destroy]  
  before_action :set_opcoes_genero, only: [:new, :create, :edit, :update]
  
  skip_before_action :verify_authenticity_token

  # GET /filmes or /filmes.json
  def index        
    if params[:busca].present?
      @resultados = Filme.buscar_filme(params[:busca])      
      respond_to do |format|
        format.js { render partial: "resultados-busca" }
      end
    else
      @filmes = Filme.all
      flash[:notice] = "Nenhum filme foi cadastrado" if @filmes.blank?
    end
    
    respond_to do |format|    
      format.html { @filmes = Filme.order(:titulo).page params[:page] }
      format.pdf { @filmes = Filme.order(:titulo) }      
    end
  end

  # GET /filmes/1 or /filmes/1.json
  def show        
  end

  # GET /filmes/new
  def new
    @filme = Filme.new
  end

  # GET /filmes/1/edit
  def edit    
  end

  # POST /filmes or /filmes.json
  def create
    @filme = Filme.new(filme_params)

    respond_to do |format|
      if @filme.save
        format.html { redirect_to filme_url(@filme)
        flash[:success] = t('filme.save') }
        format.json { render :show, status: :created, location: @filme }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @filme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /filmes/1 or /filmes/1.json
  def update
    respond_to do |format|
      if @filme.update(filme_params)
        format.html { redirect_to filme_url(@filme)
        flash[:success] = t('filme.update') }
        format.json { render :show, status: :ok, location: @filme }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @filme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filmes/1 or /filmes/1.json
  def destroy
    @filme.destroy

    respond_to do |format|
      format.html { redirect_to filmes_url
      flash[:success] = t('filme.delete') }
      format.json { head :no_content }
    end
  end
  
  private
    def set_opcoes_genero
      @opcoes_genero = Genero.all.order(:nome).pluck(:nome, :id)
    end 
    # Use callbacks to share common setup or constraints between actions.
    def set_filme
      @filme = Filme.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def filme_params
      params.require(:filme).permit(:titulo, :url_capa, :capa, :ano, :idade, :elenco, :sinopse, :genero_id, {:filme_genero => []})
    end
end

app/controllers/generos_controller.rb
class GenerosController < ApplicationController
  before_action :set_genero, only: %i[ show edit update destroy ]
  
  # GET /generos or /generos.json
  def index
    @generos = Genero.order(:nome)
  end

  # GET /generos/1 or /generos/1.json
  def show            
  end

  # GET /generos/new
  def new
    @genero = Genero.new    
  end
  
  # GET /generos/1/edit
  def edit    
  end
  
  # POST /generos or /generos.json
  def create    
      @genero = Genero.new(genero_params)      

      respond_to do |format|
        if @genero.save
          format.html
          format.json
          format.js
        else
          format.html
          format.json
          format.js
        end
      end
    
  end

  # PATCH/PUT /generos/1 or /generos/1.json
  def update
    respond_to do |format|
      if @genero.update(genero_params)
        format.html { redirect_to genero_url(@genero), notice: "Genero was successfully updated." }
        format.json { render :show, status: :ok, location: @genero }
        format.js
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @genero.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /generos/1 or /generos/1.json
  def destroy
    @genero.destroy

    respond_to do |format|
      format.html { redirect_to generos_url, notice: "Genero was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private    
    # Use callbacks to share common setup or constraints between actions.
    def set_genero
      @genero = Genero.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def genero_params
      params.require(:genero).permit(:nome)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}", role: "alert") do 
        concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
        concat message 
      end)
    end
    nil
  end
end

app/helpers/filmes_helper.rb
module FilmesHelper
end

app/helpers/generos_helper.rb
module GenerosHelper
    def devolve_genero(filme_id)
        Genero.order(:nome).where(id: filme_id).pluck(:nome).join(', ')
    end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/filmes/_form.html.erb
<%= form_with(model: filme, local: true) do |form| %>
  <% if filme.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h2 class="alert-heading"><em>"Houston, we have a problem"</em></h2>
      <p class="mb-0"><%= pluralize(filme.errors.count, "inconsistência", plural: "inconsistências") %> impediu que o filme fosse adicionado:</p>      
      <hr>
      <p class="mb-0">Abaixo, uma lista dos campos destacados que precisam ser alterados/preenchidos</p>
      <ul>
        <% filme.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <form>
    <div class="form-group">        
      <%= form.label :capa %>   
      <div>
        <%= image_tag url_for(@filme.capa), class: "img-thumbnail", width: 200 if @filme.capa.attached? %>    
        <br>
        <%= form.file_field :capa, class: "form-control-file" %>
      </div>
    </div>
    <div class="form-row">      
      <div class="form-group col-7">
        <%= form.label :titulo %> <font size="3" color="red">*</font>
        <%= form.text_field :titulo, class:"form-control", placeholder:"Ex: Star Wars", required: true %>        
        
      </div>
      <div class="form-group col">
        <%= form.label :ano %> <font size="3" color="red">*</font>
        <%= form.text_field :ano, class:"small form-control", required: true %>
      </div>      
      <div class="form-group col">
        <%= form.label :genero %> <font size="3" color="red">*</font> <small>(<%= link_to t('links.new'), new_genero_path, class:"btn-link", data: { remote: true } %>)</small>
        <div>          
          <%= form.select("filme_genero", @opcoes_genero, { include_blank: false, include_hidden: false }, class:"form-control selectpicker form-control-sm", multiple: true, required: true) %>                    
        </div>
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-2">
        <%= form.label :idade %> <font size="3" color="red">*</font>
        <%= form.text_field :idade, class:"form-control", placeholder:"Ex: Livre, 12, 16, 18", required: true %>
      </div>
      <div class="form-group col">
        <%= form.label :elenco %>
        <%= form.text_field :elenco, class:"form-control" %>
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col">
        <%= form.label :sinopse %>
        <%= form.text_area :sinopse, class:"form-control", rows:3 %>
      </div>    
    </div>  
    <div class="actions">
      <%= form.submit class:"btn btn-success text-light btn-sm" %>
        <%= link_to t('links.back'), filmes_path, class:"btn btn-primary text-light btn-sm" %>
    </div>
    <font size="3" color="red">*</font> <i>Preenchimento obrigatório</i>
  </form>
<% end %>

app/views/filmes/_resultados-busca.js.erb
$("#filmes-table").hide();
$("#resultados-busca").html("<%= j render :partial => 'resultados' %>");

app/views/filmes/_resultados.html.erb
<% unless @resultados.nil? %>
  <div class="align-middle">
    <h4>
      Sua busca encontrou <%= pluralize(@resultados.count, 'filme', plural: 'filmes') %><br>
      <small><%= link_to t('links.home'), filmes_path, class:"btn btn-light btn-sm" %></small>
    </h4>  
  </div>
  <div class="row jumbotron jumbotron-fluid justify-content-center">
    <% @resultados.each do |filme| %>
      <div class="mx-auto">
        <%= link_to filme, class:"card-link" do %>
          <div class="card" style="width: 10rem;">          
            <%= image_tag filme.capa, class: "card-img-top" if filme.capa.attached? %>              
            <div class="card-body">
              <h5 class="card-title"><%= filme.titulo %></h5>              
            </div>
          </div>
          <br>
        <% end %>
      </div>
    <% end %>    
  </div>  
<% else %>  
  <script>
    $(document).ready(function(){ $("#modalFilmeNaoEncontrado").modal('show'); });
  </script>
  <div id="modalFilmeNaoEncontrado" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Filme não cadastrado</h5>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
          <p>Desculpe, mas o filme <strong><%= params[:busca] %></strong> não consta na nossa base de dados.</p>
          <p>Que tal cadastrá-lo agora?</p>        
          <%= link_to t('links.newmovie'), new_filme_path, class:"btn btn-success text-light btn-sm" %>
          <small><%= link_to t('links.home'), filmes_path, class:"btn btn-light btn-sm" %></small>
        </div>
      </div>
    </div>  
  </div>  
<% end %>

app/views/filmes/edit.html.erb
<h1 class="display-4"><%= @filme.titulo %></h1>

<%= render 'form', filme: @filme %>

app/views/filmes/index.html.erb
<h1 class="display-4"><%= t('links.movies')%></h1>
<%= link_to t('links.newmovie'), new_filme_path, class:"btn btn-success text-light btn-sm" %>
<%= link_to 'Imprimir Catálogo', filmes_path(format: :pdf), class:"btn btn-primary text-light btn-sm", target: :_blank  %>
<br /><br />

<%= form_tag(filmes_path, method: :get, remote: true) do %>  
  <%= text_field_tag :busca, nil, class: "form-control form-control-sm form-control-borderless", placeholder:"Título do filme" %>     
<% end %>
<br>

<div id="filmes-table">
<p id="notice"><%= flash_messages %></p>
  <div class="row jumbotron jumbotron-fluid justify-content-center">    
    <% @filmes.each do |filme| %>
      <div class="mx-auto">
        <%= link_to filme, class:"card-link" do %>
          <div class="card" style="width: 15rem;">          
            <%= image_tag filme.capa, class: "card-img-top" if filme.capa.attached? %>              
            <div class="card-body">
              <h5 class="card-title"><%= filme.titulo %></h5>
              <p class="text-muted"><%= filme.ano %> · <%= filme.idade %> · <%= devolve_genero(filme.filme_genero) %></p>
              <p class="card-text text-truncate" style="max-width: 20rem;"><%= filme.sinopse %></p>                    
            </div>
          </div>          
        <% end %>
      </div>
    <% end %>    
  </div>    
    <div class="pagination justify-content-center">
      <%= paginate @filmes %>
    </div>  
</div>

<div id="resultados-busca"></div>

app/views/filmes/new.html.erb
<h1 class="display-4"><%= t('links.new') %></h1>

<%= render 'form', filme: @filme %>

app/views/filmes/show.html.erb
<p id="notice"><%= notice %></p>
<form class="jumbotron">
  <div class="form-group">
    <h1 class="display-4"><%= label_tag nil, @filme.titulo %></h1>    
  </div>   

  <div class="row">
    <div class="col-md-auto">
      <div class="form-group">            
        <%= image_tag url_for(@filme.capa), class: "img-thumbnail", width: 250 if @filme.capa.attached? %>                
      </div>
    </div>
    <div class="col">
      <div class="form-group">    
        <strong><%= label_tag nil, @filme.class.human_attribute_name(:sinopse) %></strong>
        <br>
        <blockquote class="blockquote text-justify"><em><%= @filme.sinopse %></em></blockquote>

        <div class="col">
          <div class="row">
            <div class="form-group">    
              <strong><%= label_tag nil, @filme.class.human_attribute_name(:ano) %></strong>
              <%= text_field_tag nil, @filme.ano, class:"form-control-plaintext", disabled: true %>
            </div>

            <div class="form-group">    
              <strong><%= label_tag nil, @filme.class.human_attribute_name(:genero) %></strong>
              <% if @filme.filme_genero.nil? %>
                <%= text_field_tag nil, "Sem gênero cadastrado", class:"form-control-plaintext font-italic", disabled: true %>
              <% else %>
                <%= text_field_tag nil, devolve_genero(@filme.filme_genero), class:"form-control-plaintext", disabled: true %>
              <% end %>
            </div>

            <div class="form-group">    
              <strong><%= label_tag nil, @filme.class.human_attribute_name(:idade) %></strong>
              <%= text_field_tag nil, @filme.idade, class:"form-control-plaintext", disabled: true %>
            </div>
            <div class="col">
              <div class="form-group">    
                <strong><%= label_tag nil, @filme.class.human_attribute_name(:elenco) %></strong>
                <%= text_field_tag nil, @filme.elenco, class:"form-control-plaintext", disabled: true %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%= link_to t('links.edit'), edit_filme_path(@filme), class:"btn btn-success text-light btn-sm" %>
  <%= link_to t('links.delete'), @filme, method: :delete, data: { confirm: "Deseja remover o filme #{@filme.titulo}?" }, class:"btn btn-danger text-light btn-sm" %>
  <%= link_to t('links.back'), filmes_path, class:"btn btn-primary text-light btn-sm" %>
</form>

app/views/filmes/show.js.erb
$('.modal-body').html('<%= j render :partial => 'generos/form'%>');
$('.modal-header').remove(); 

app/views/generos/_form.html.erb
<div id="novoGenero-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= t('links.newgender') %></h5>        
        <button type="button" class="close" data-dismiss="modal">x</button>        
      </div>
      <%= form_for @genero, remote: true do |f| %>
        <div class="modal-body">
          <%= f.label :nome %>
          <%= f.text_field :nome, class: "form-control" %>
        </div>
        <div class="modal-footer">
          <%= f.submit t('links.insert'), class: "btn btn-primary btn-sm" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/generos/create.js.erb
<% if @genero.errors.blank? %>   
  $('#novoGenero-modal').modal('hide');       
  $(document).on('hidden.bs.modal','#novoGenero-modal', function () {
    const selectWrapper = document.getElementById('filme_filme_genero');

    fetch('/generos.json')
    .then(res => res.json())
    .then(jsonData => {
      if (!jsonData) {return}
      selectWrapper.innerHTML = '';

      const fragment = document.createDocumentFragment()

      jsonData.forEach(genero => {
        let {id, nome} = genero;

        let generoOption = document.createElement('option');
        generoOption.value = genero.id;
        generoOption.innerText = genero.nome;
        fragment.appendChild(generoOption);
      })

      selectWrapper.append(fragment)      
    })
  });
  
<% else %>
  alert("error: <%= @genero.errors.full_messages.first %>");
<% end %>

app/views/generos/edit.html.erb
<h1>Editing Genero</h1>

<%= render 'modal', genero: @genero %>

<%= link_to 'Show', @genero %> |
<%= link_to 'Back', generos_path %>

app/views/generos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Generos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @generos.each do |genero| %>
      <tr>
        <td><%= genero.nome %></td>
        <td><%= link_to 'Show', genero %></td>
        <td><%= link_to 'Edit', edit_genero_path(genero) %></td>
        <td><%= link_to 'Destroy', genero, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Genero', new_genero_path, remote: true %>

app/views/generos/new.js.erb
$('<%= j render "form" %>').modal();

app/views/generos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @genero.nome %>
</p>

<%= link_to 'Edit', edit_genero_path(@genero) %> |
<%= link_to 'Back', generos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HOLYFLIX - Gerenciador de Filmes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <br>
    <div class="container-fluid"> 
      <%= yield %>
    </div>
    <body>
</html>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <div class="row">
    <div class="col-md-auto">
      <h1 class="display-1 text-danger"><%= t('app.name') %></h1>
      <p class="lead"><%= t('app.holyflix')%></p>
      <p class="lead"><%= t('app.desc') %></p>  
      <hr class="my-4">            
      <%= link_to t('app.access'), filmes_path, class:"btn btn-primary text-light", role:"button" %>  
    </div>
    <div class="col">
      <% @capas = Filme.all.shuffle %>            
      <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner text-center">
          <div class="carousel-item active">
            <% @capas.first(1).each do |filme| %>                          
            <%= image_tag filme.capa, class: "img-thumbnail d-block mx-auto", width: 300 if filme.capa.attached? %>
              <h3><small class="text-muted"><em><%= filme.titulo %></em></small></h3>                          
            <% end %>
          </div>
          <% @capas.drop(1).each do |filme| %>
            <div class="carousel-item">
              <%= image_tag filme.capa, class: "img-thumbnail d-block mx-auto", width: 300 if filme.capa.attached? %>
              <h3><small class="text-muted"><em><%= filme.titulo %></em></small></h3>
            </div> 
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>